services:
  vote:
    image: voteapp
    container_name: "voteapp"
    networks: 
      - front

  nginx:
    image: nginx
    container_name: "nginxserver"
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - front
      - back
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  
    depends_on:
      - vote
      
  redis:
    image: redis:alpine
    container_name: "redis"
    networks: 
      - front
    volumes:
      - ./vote:/usr/local/app

  worker:
    image: voteapp-worker
    container_name: "voteapp-worker"
    depends_on:
      - redis
      - db
    networks:
      - back
      - front

  db:
    image: postgres:15-alpine
    container_name: "db"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voteapp
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - back
      - front

  result:
    image: voteapp-result
    container_name: "voteapp-result"
    ports:
      - "5005:80"
    depends_on:
      - db
    restart: always
    networks:
      - back
      - front


volumes:
  db_data:

networks:
  front:
  back: